# -*- coding: utf-8 -*-
"""Based-ROOP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o2LG8e_kg174vPjI_OQ9Xs1r8U4BSk-w

#Clone roop repo and install dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/based9based/roop
# %cd roop
!pip install -r requirements.txt

"""#download model"""

!wget https://civitai.com/api/download/models/85159 -O inswapper_128.onnx

"""#Deepfake"""

!python run.py --target /content/NSF.mp4 --source /content/AS.jpg -o /content/swapped.mp4 --execution-provider cuda --frame-processor face_swapper face_enhancer

